Repository osquery/osquery-site, pull requests merged in 2020-04, with the labels that each got.

#166 Correct keyserver URL for APT repository
  src/data/pages/downloads.json
Labels: documentation

#169 4.3.0 packages
  src/data/osquery_metadata.json
  src/data/osquery_package_versions/4.3.0.json
  src/data/osquery_schema_versions/4.3.0.json
Labels: new-release

#170 Update windows hash 4.3.0
  src/data/osquery_package_versions/4.3.0.json
Labels: bug
